"""fabrication_spec.txt -- the plain-text sheet that goes to the foundry.

One file, human-readable, self-contained: what the part is, the
material it was designed for (with the refractive-index model and the
index at every design wavelength), the relief (rings, pitch, height
quantum, levels), the lithography encoding and dose map, the design's
validated performance, the accompanying files with checksums, and the
complete per-ring height map (one line per ring). Everything comes from
the run folder; the fields the design does not fix (substrate, resist
lot, anti-reflection coating, delivery format of the wafer) are printed
as explicit TO-BE-AGREED lines so nobody mistakes an absent number for
an unimportant one.
"""
from __future__ import annotations

import importlib
import json
import os
import sys
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

import numpy as np

from . import __version__
from .encode import Encoding
from .rings import RingTable

HERE = os.path.dirname(os.path.abspath(__file__))
PKG_ROOT = os.path.dirname(os.path.dirname(HERE))
IndexFn = Callable[[Any], np.ndarray]


@dataclass(frozen=True)
class MaterialSpec:
    """The resist the design assumed. ``index`` is the model the design
    FOM, the RS verification and the OpticStudio DLLs all use."""
    name: str
    description: str
    formula: str
    index: IndexFn
    source: str          # where the model was imported from (echoed)

    @classmethod
    def design_default(cls, pkg_root: str = PKG_ROOT) -> "MaterialSpec":
        """AZ4562 from ``01_design_oo/mdl/material.py`` when present (the
        model the design was optimized with), else the same Cauchy fit
        restated here."""
        oo = os.path.join(pkg_root, "01_design_oo")
        try:
            if oo not in sys.path:
                sys.path.insert(0, oo)
            mat = importlib.import_module("mdl.material")
            fn, src = mat.n_az4562, "01_design_oo/mdl/material.py"
        except Exception:
            fn, src = (lambda lam: 1.594 + 0.01152 / np.asarray(lam, float) ** 2), \
                "gdsout.spec (fallback, same coefficients)"
        return cls(
            name="AZ 4562 positive photoresist (grayscale-exposed relief)",
            description="the photoresist of Xiao et al., Light Sci. Appl. 11:323 (2022);\n"
                        "                     dispersion from their Fig. S8, average n ~ 1.63 "
                        "over 400-1100 nm",
            formula="n(lam) = 1.594 + 0.01152 / lam^2   (lam in um; real part; "
                    "absorption not modelled)",
            index=fn, source=src)


class FabricationSpec:
    """Writer of fabrication_spec.txt for one run folder."""

    def __init__(self, run_dir: str, cfg: Dict[str, Any], table: RingTable,
                 encoding: Encoding, material: Optional[MaterialSpec] = None) -> None:
        self.run_dir = run_dir
        self.cfg = cfg
        self.table = table
        self.encoding = encoding
        self.material = material or MaterialSpec.design_default()

    # -- sections ------------------------------------------------------------------
    def _wavelengths(self) -> np.ndarray:
        c = self.cfg
        lams = c.get("target_wavelengths_um") or c.get("verify_wavelengths_um") or []
        return np.asarray(lams, dtype=float)

    def header(self) -> List[str]:
        c, t = self.cfg, self.table
        der = c.get("derived", {})
        D = float(c.get("diameter_um", t.radius_um * 2))
        F = der.get("focal_um")
        na = der.get("na")
        return [
            "=" * 78,
            "FABRICATION SPECIFICATION -- achromatic multilevel diffractive lens (MDL)",
            "=" * 78,
            "design name        : %s" % c.get("name"),
            "design run         : %s" % os.path.abspath(self.run_dir),
            "generated by       : gdsout %s (03_tapeout_oo/export_gds.py)" % __version__,
            "",
            "1. OPTICAL FUNCTION",
            "-" * 78,
            "type               : rotationally symmetric, flat, multilevel diffractive",
            "                     lens (staircase of concentric rings), achromatic over",
            "                     the band below by frequency-domain coherence optimization",
            "clear aperture     : D = %.3f mm (R = %.3f mm; %d rings x %.4f um)"
            % (D / 1000, D / 2000, t.n, t.delta_um),
            "focal length       : F = %s mm (in air, design value)"
            % ("%.3f" % (F / 1000) if F else "n/a"),
            "numerical aperture : NA = %s" % ("%.4f" % na if na else "n/a"),
            "wavelength band    : %.0f - %.0f nm" % (1000 * c.get("lam_min_um", 0),
                                                     1000 * c.get("lam_max_um", 0)),
            "design comb        : %s" % (", ".join("%.0f" % (1000 * v) for v in
                                                    (c.get("target_wavelengths_um") or []))
                                          + " nm" if c.get("target_wavelengths_um")
                                          else "continuous band"),
            "illumination       : normal-incidence plane wave (the lens is designed for",
            "                     unit-amplitude, on-axis illumination from the flat side)",
            "",
        ]

    def material_section(self) -> List[str]:
        m = self.material
        lams = self._wavelengths()
        rows = ["2. MATERIAL", "-" * 78,
                "relief material    : %s" % m.name,
                "                     %s" % m.description,
                "index model        : %s" % m.formula,
                "model source       : %s" % m.source,
                "index at the design wavelengths (real part):"]
        if lams.size:
            n = m.index(lams)
            for i in range(0, lams.size, 4):
                rows.append("                     " + "   ".join(
                    "%.0f nm: %.4f" % (1000 * l, v) for l, v in zip(lams[i:i + 4], n[i:i + 4])))
        rows += [
            "substrate          : TO BE AGREED (fused silica / borosilicate; the design",
            "                     assumes the relief on a flat, parallel, transparent",
            "                     substrate -- substrate thickness does not enter the",
            "                     optical design, only the working distance)",
            "resist lot / bake  : TO BE AGREED (the index above must be met to +/-0.01;",
            "                     a shift dn changes the phase per level by dn/(n-1) ~ 1.6 dn)",
            "AR coating         : none assumed",
            "",
        ]
        return rows

    def relief_section(self) -> List[str]:
        c, t = self.cfg, self.table
        m = t.levels()
        return [
            "3. SURFACE RELIEF (what to write)",
            "-" * 78,
            "geometry           : N = %d concentric rings, ring width DELTA = %.4f um,"
            % (t.n, t.delta_um),
            "                     ring i covers radius [i*DELTA, (i+1)*DELTA), i = 0..%d" % (t.n - 1),
            "height per ring    : h_i = m_i x dh,  dh = %.4f um (height quantum),"
            % t.dh_um,
            "                     gray level m_i integer in 0..%d (%d of the %d levels occur)"
            % (int(m.max()), int(np.unique(m).size),
               int(round(c.get("h_max_um", t.h_um.max()) / t.dh_um)) + 1),
            "max relief height  : %.4f um (design cap H = %s um)"
            % (float(t.h_um.max()), c.get("h_max_um")),
            "height reference   : h = 0 is the substrate / fully cleared level; heights",
            "                     are resist thickness remaining above it",
            "profile            : each ring is a flat step (binary-optics staircase); ring",
            "                     walls vertical; no smoothing between rings intended",
            "height tolerance   : TO BE AGREED -- guidance: |dh_error| <= dh/2 = %.3f um per"
            % (t.dh_um / 2),
            "                     ring keeps every ring on its design level; a global",
            "                     scale error s in height acts like an index error (n-1)s",
            "lateral tolerance  : TO BE AGREED -- guidance: ring edge placement within",
            "                     +/- 0.1 um (5 %% of DELTA) across the full %.1f mm radius"
            % (t.radius_um / 1000),
            "height map         : section 7 below (one line per ring) and height_map.csv",
            "",
        ]

    def litho_section(self) -> List[str]:
        s = self.encoding
        t = self.table
        m_max = int(t.levels().max())
        rows = ["4. LAYOUT FILES AND ENCODING", "-" * 78,
                "GDSII              : %s.gds (user unit 1 um, database unit 1 nm)" % self.cfg.get("name"),
                "encoding           : %s" % s.describe(),
                "dose map           : <name>.gds.layers.csv -- gds_layer, gray_level,",
                "                     height_um, height_frac_of_max; the writer's dose /",
                "                     gray value per layer must produce the height_um column",
                "layers in file     : %s" % ("1..%d (level 0 = no resist, not drawn)" % m_max
                                             if s.NAME == "index" and not s.draw_zero else
                                             "0..%d" % m_max if s.NAME == "index" else
                                             "1..%d nested (layer L = height >= L x dh)" % m_max),
                "polygons           : merged annuli (adjacent rings of equal level joined);",
                "                     circles approximated with chord error <= 0.02 um",
                ""]
        return rows

    def performance_section(self) -> List[str]:
        rows = ["5. DESIGN PERFORMANCE (scalar-diffraction verification, stage 2a)", "-" * 78]
        vm = os.path.join(self.run_dir, "rs", "verify_metrics.json")
        if not os.path.exists(vm):
            rows += ["(rs/verify_metrics.json not found -- run 02_validation_rs_oo/run_verify.py",
                     " on this run folder to fill this section)", ""]
            return rows
        with open(vm) as fh:
            v = json.load(fh)
        rows.append("  lam(nm)   focus z(mm)   FWHM(um)   eff(3xFWHM)   Strehl-like   shape-Strehl")
        for i, lam in enumerate(v["lam_um"]):
            rows.append("  %5.0f     %9.3f     %6.2f       %.3f          %.3f          %.3f"
                        % (1000 * lam, v["z_peak_um"][i] / 1000, v["fwhm_um"][i],
                           v["eff_3fwhm"][i], v["strehl_like"][i], v["strehl_shape"][i]))
        rows.append("  (eff = power in a disc of diameter 3 FWHM / incident power; Strehl-like =")
        rows.append("   peak vs ideal lens incl. efficiency; shape-Strehl = window-normalized)")
        rows.append("  RS ring quadrature: %s; design J (objective) = %.4f"
                    % (v.get("rs_ring_quadrature"), v.get("J_objective", float("nan"))))
        mt = os.path.join(self.run_dir, "rs", "verify_mtf.npz")
        if os.path.exists(mt):
            z = np.load(mt)
            rows.append("  polychromatic MTF area ratio to the diffraction limit: %.3f"
                        % float(z["mtf_quality_poly"]))
        rows.append("")
        return rows

    def files_section(self, files: Dict[str, str], checksums: Dict[str, str]) -> List[str]:
        rows = ["6. FILES IN THIS PACKAGE (SHA256)", "-" * 78]
        for label, path in files.items():
            name = os.path.basename(path)
            rows.append("  %-28s %s" % (name, checksums.get(name, "")))
        rows.append("")
        return rows

    def height_map_section(self) -> List[str]:
        t = self.table
        m = t.levels()
        rows = ["7. HEIGHT MAP -- one line per ring (radii and heights in um)", "-" * 78,
                "  ring     r_in        r_out     level    height"]
        for i in range(t.n):
            rows.append("  %5d  %10.4f  %10.4f  %6d  %9.4f"
                        % (i, i * t.delta_um, (i + 1) * t.delta_um, int(m[i]), m[i] * t.dh_um))
        rows.append("")
        rows.append("end of specification")
        return rows

    # -- file ---------------------------------------------------------------------------
    def write(self, path: str, files: Dict[str, str], checksums: Dict[str, str]) -> str:
        lines = (self.header() + self.material_section() + self.relief_section()
                 + self.litho_section() + self.performance_section()
                 + self.files_section(files, checksums) + self.height_map_section())
        with open(path, "w") as fh:
            fh.write("\n".join(lines) + "\n")
        return path
